# ansible-playbook --connection=local --inventory 127.0.0.1, playbook.yml
- name: Complete provisioning of my development environment
  hosts: 127.0.0.1
  tasks:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: Install node
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node"
        creates=/home/{{ ansible_user_id }}/.nvm/alias

    - name: Install Homebrew
      shell: >
        /bin/bash -c "export NONINTERACTIVE=1; $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        creates=/home/linuxbrew/.linuxbrew/

    - name: Configure .zshrc for Homebrew
      shell: >
        /bin/bash -c "(echo 'eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"') >> $HOME/.zshrc; touch $HOME/.homebrew.configured"
        creates=/home/{{ ansible_user_id }}/.homebrew.configured

    - name: Install packages using Homebrew
      community.general.homebrew:
        name:
          - tmux
          - fzf
          - starship
          - hugo
          - zsh-autosuggestions
          - wakeonlan
          - bat

    - name: Configure .zshrc for Starship.rs
      shell: >
        /bin/bash -c "echo 'eval \"\$(starship init zsh)\"' >> ~/.zshrc; touch $HOME/.starship.configured"
        creates=/home/{{ ansible_user_id }}/.starship.configured

    - name: Configure .zshrc for fzf
      shell: >
        /bin/bash -c "echo 'source <(fzf --zsh)' >> ~/.zshrc; touch $HOME/.fzf.configured"
        creates=/home/{{ ansible_user_id }}/.fzf.configured

    - name: Configure .zshrc for zsh-autosuggestions
      shell: >
        /bin/bash -c "echo 'source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh' >> ~/.zshrc; touch $HOME/.zsh-autosuggestions.configured"
        creates=/home/{{ ansible_user_id }}/.zsh-autosuggestions.configured

    - name: Load tmux TPM plugins automatically
      shell: >
        /usr/bin/zsh -c "source ~/.zshrc && ~/.tmux/plugins/tpm/bin/install_plugins"
