# ansible-playbook --connection=local --inventory 127.0.0.1, playbook-clone-repos.yml
# You need an SSH key first - once created, add the .pub key to GitHub
# ssh-keygen -t ed25519 -C "your_email"
- name: Clone all my repos
  hosts: 127.0.0.1
  tasks:
    - name: www-jasonsblog
      git:
        repo: git@github.com:jasondchambers/www-jasonsblog.git
        accept_newhostkey: true
        dest: ~/repos/www-jasonsblog
    - name: www-art
      git:
        repo: git@github.com:jasondchambers/www-art.git
        accept_newhostkey: true
        dest: ~/repos/www-art
    - name: www-house
      git:
        repo: git@github.com:jasondchambers/www-house.git
        accept_newhostkey: true
        dest: ~/repos/www-house
    - name: myresume
      git:
        repo: git@github.com:jasondchambers/myresume.git
        accept_newhostkey: true
        dest: ~/repos/myresume
    - name: wakeupmachine
      git:
        repo: git@github.com:jasondchambers/wakeupmachine.git
        accept_newhostkey: true
        dest: ~/repos/wakeupmachine
    - name: deploytool
      git:
        repo: git@github.com:jasondchambers/deploytool.git
        accept_newhostkey: true
        dest: ~/repos/deploytool
